#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata":{"name": "kubevip"}})
---
data:
  range-global: #@ data.values.vip_range
