---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
spec:
  packageRef:
    refName: contour.community.tanzu.vmware.com
    versionSelection:
      constraints: 1.18.1
      prereleases: {}
  serviceAccountName: tce-extensions-installer
  values:
  - secretRef:
      name: contour-values
