---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
spec:
  packageRef:
    refName: external-dns.community.tanzu.vmware.com
    versionSelection:
      constraints: 0.8.0
      prereleases: {}
  serviceAccountName: tce-extensions-installer
  values:
  - secretRef:
      name: external-dns-values
