---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: grafana
spec:
  packageRef:
    refName: grafana.community.tanzu.vmware.com
    versionSelection:
      constraints: 7.5.7
      prereleases: {}
  serviceAccountName: tce-extensions-installer
  values:
  - secretRef:
      name: grafana-values
